// Tier-1 file: agents can update copy here freely. All user-visible strings live here
// (eventually for i18n; for now just to keep them out of components).

export const COPY = {
  appName: 'ClickKeep',
  tagline: 'A free, universal group metronome',
  solo: {
    title: 'Solo',
    play: 'Play',
    stop: 'Stop',
    tap: 'Tap',
    tapHint: 'Tap to set tempo',
    bpm: 'BPM',
    beatsPerBar: 'Beats per bar',
    mute: 'Mute click',
    unmute: 'Unmute click',
    muted: 'Muted',
    visualOn: 'Hide visual flash',
    visualOff: 'Show visual flash',
    hapticOn: 'Disable haptic',
    hapticOff: 'Enable haptic',
    tone: 'Tone',
    accentPatternLabel: 'Per-beat accent pattern (click to cycle)',
  },
  tempoMap: {
    trigger: 'MIDI',
    triggerLoaded: 'MIDI loaded',
    title: 'MIDI tempo map',
    load: 'Load MIDI',
    replace: 'Load a different file',
    clear: 'Clear tempo map',
    loaded: 'Tempo map',
    dropHint: 'Drop a .mid file, or tap to choose',
    parseError: 'Could not read MIDI file.',
    empty: 'No tempo changes found in this MIDI.',
    summaryChanges: 'tempo changes',
    summaryLength: 'length',
    summaryRange: 'BPM range',
    useThis: 'Use this map',
  },
  session: {
    trigger: 'Session',
    create: 'Create session',
    createTitle: 'Start a session',
    createBlurb: 'Open a room. Share the 4-letter code with anyone you want clicking with you.',
    join: 'Join session',
    joinTitle: 'Join a session',
    joinBlurb: 'Enter the 4-letter code your host shared.',
    codeLabel: 'Session code',
    codePlaceholder: 'ABCD',
    copy: 'Copy code',
    copied: 'Copied',
    share: 'Share',
    leave: 'Leave',
    membersOne: 'member',
    membersMany: 'members',
    memberHint: 'Session owner controls tempo.',
    ownerBadge: 'you are the owner',
    invalidChar: 'Use letters and digits only (no I, L, O, 0, 1).',
    needFour: 'Enter all 4 characters.',
    activityToggle: 'Member activity',
    activityEmpty: 'No activity yet',
    activityJoined: 'joined',
    activityLeft: 'left',
  },
  theme: {
    light: 'Light',
    dark: 'Dark',
    system: 'System',
  },
} as const;
